[env]
WINIT_X11_SCALE_FACTOR = "1"

[font]
size = 16.0

[font.bold]
family = "Fantasque Sans Mono"
style = "Bold"

[font.italic]
family = "Fantasque Sans Mono"
style = "Italic"

[font.normal]
family = "Fantasque Sans Mono"
style = "Regular"
