---
- name: Basic System Setup
  hosts: all
  become: true
  become_method: doas
  vars:
    user: patrick
  tasks:
    - name: Packages Installed
      package:
        name: "{{ item }}"
      loop:
        - git
        - wget
    - name: Dotfiles Copied
      copy:
        src: "{{ item.src }}"
        dest: "/home/{{ user }}/{{ item.dest }}"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0644'
      loop:
        - src: vimrc
          dest: .vimrc
        - src: bashrc
          dest: .bashrc
