---
- name: Setup Suckless Desktop
  hosts: all
  become: true
  become_method: doas
  vars:
    user: patrick
    suckless:
      - name: dwm
        version: 6.6
        url: https://dl.suckless.org/dwm/dwm-6.6.tar.gz
      - name: dmenu
        url: https://dl.suckless.org/tools/dmenu-5.4.tar.gz
        version: 5.4
      - name: st
        url: https://dl.suckless.org/st/st-0.9.3.tar.gz
        version: 0.9.3
      - name: slstatus
        url: https://dl.suckless.org/tools/slstatus-1.1.tar.gz
        version: 1.1
      - name: slock
        url: https://dl.suckless.org/tools/slock-1.6.tar.gz
        version: 1.6
  tasks:
    - name: Packages Installed
      package:
        name: "{{ item }}"
      loop:
        - fantasque-sans
        - alacritty
    - name: Suckless Folder Created
      file:
        path: "/home/{{ user }}/suckless"
        state: directory
        mode: '0755'
        owner: "{{ user }}"
        group: "{{ user }}"
    - name: Source Code Downloaded
      get_url:
        url: "{{ item.url }}"
        dest: "/home/{{ user }}/suckless/{{ item.name }}.tar.gz"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0644'
      loop: "{{ suckless }}"
    - name: Source Code Unpacked
      command:
        chdir: "/home/{{ user }}/suckless"
        cmd: "tar xzf {{ item.name }}.tar.gz"
        creates: "/home/{{ user }}/suckless/{{ item.name }}-{{ item.version }}"
      loop: "{{ suckless }}"
    - name: Source Folders Owned
      file:
        path: "/home/{{ user }}/suckless/{{ item.name }}-{{ item.version }}"
        state: directory
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0755'
      loop: "{{ suckless }}"
    - name: Custom Files Copied
      copy:
        src: "{{ item.src }}"
        dest: "/home/{{ user }}/suckless/{{ item.dest }}"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0644'
      loop:
        - src: dwm/config.mk
          dest: dwm-6.6/config.mk
        - src: dwm/config.h
          dest: dwm-6.6/config.h
        - src: dmenu/config.mk
          dest: dmenu-5.4/config.mk
        - src: st/config.mk
          dest: st-0.9.3/config.mk
        - src: st/config.h
          dest: st-0.9.3/config.h
        - src: slstatus/config.mk
          dest: slstatus-1.1/config.mk
        - src: slstatus/config.h
          dest: slstatus-1.1/config.h
        - src: slock/config.mk
          dest: slock-1.6/config.mk
        - src: slock/config.h
          dest: slock-1.6/config.h
    - name: Software Compiled and Installed
      command:
        chdir: "/home/{{ user }}/suckless/{{ item.name }}-{{ item.version }}"
        cmd: "make install"
        creates: "/usr/local/bin/{{ item.name }}"
      loop: "{{ suckless }}"
    - name: XSession File
      copy:
        src: xsession
        dest: "/home/{{ user }}/.xsession"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0644'
    - name: Alacritty Config File
      copy:
        src: alacritty.toml
        dest: "/home/{{ user }}/.alacritty.toml"
        owner: "{{ user }}"
        group: "{{ user }}"
        mode: '0644'
